// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID        int32
	UserID    uuid.UUID
	Total     string
	Status    string
	Address   string
	CreatedAt time.Time
}

type OrderItem struct {
	ID        int32
	OrderID   int32
	ProductID int32
	Quantity  int32
	Price     string
}

type Product struct {
	ID          int32
	Name        string
	Description string
	Image       string
	Price       string
	Quantity    int32
	CreatedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt time.Time
}
