name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DBSTRING: ${{ secrets.DBSTRING }}

    steps:
      - name: check go code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install goose
        run: "go install github.com/pressly/goose/v3/cmd/goose@latest"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Build docker and push image"
        run: "gcloud builds submit --tag asia-southeast1-docker.pkg.dev/practice-423410/ecom-ar-repo/ecom:TAG . "

      - name: Deploy to Cloud Run
        run: gcloud run deploy speedrun --image asia-southeast1-docker.pkg.dev/practice-423410/practice-ar-repo/ecom:TAG --region asia-southeast1 --allow-unauthenticated --project practice-423410 --max-instances=4
